import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "Arial, sans-serif",
    background: "#f4efe6",
    minHeight: "100vh",
    padding: "clamp(12px, 3vw, 24px)",
    boxSizing: "border-box",
  },
  card: {
    background: "#fffaf2",
    borderRadius: 10,
    padding: "clamp(14px, 3vw, 20px)",
    boxShadow: "0 1px 4px rgba(80, 62, 43, 0.1)",
    border: "1px solid #e4d8c7",
    maxWidth: 960,
    margin: "0 auto",
    width: "100%",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
  },
  input: {
    width: "100%",
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid #d6c7b4",
    background: "#fffdf8",
    color: "#2f2a24",
    fontSize: 14,
    boxSizing: "border-box",
    minWidth: 0,
  },
  button: {
    background: "#3f6f58",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  secondaryButton: {
    background: "#efe5d6",
    color: "#2f2a24",
    border: "1px solid #d6c7b4",
    padding: "8px 12px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  title: {
    marginTop: 0,
    color: "#2f2a24",
  },
  section: {
    border: "1px solid #e4d8c7",
    borderRadius: 10,
    padding: 14,
    marginTop: 14,
    background: "#fbf6ec",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  small: {
    color: "#776b5d",
    fontSize: 13,
  },
  error: {
    padding: 10,
    borderRadius: 8,
    background: "#fee2e2",
    color: "#991b1b",
    border: "1px solid #fecaca",
    marginBottom: 12,
  },

  cardTitle: {
    marginTop: 0,
    marginBottom: 12,
    color: "#2f2a24",
  },
  sectionTitle: {
    marginTop: 0,
    marginBottom: 10,
    color: "#2f2a24",
  },
  field: {
    marginBottom: 14,
  },
  label: {
    display: "block",
    marginBottom: 6,
    fontWeight: 600,
    color: "#4f463c",
  },
  textarea: {
    width: "100%",
    minHeight: 90,
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid #d6c7b4",
    background: "#fffdf8",
    color: "#2f2a24",
    resize: "vertical",
    fontSize: 14,
    boxSizing: "border-box",
  },
  primaryButton: {
    background: "#3f6f58",
    color: "#fff",
    border: "none",
    padding: "8px 12px",
    borderRadius: 8,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 14,
  },
  removeButton: {
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    padding: "6px 9px",
    borderRadius: 8,
    cursor: "pointer",
    marginTop: 8,
    fontSize: 12,
    fontWeight: 600,
  },
  formInfo: {
    padding: 12,
    borderRadius: 10,
    background: "#fbf6ec",
    marginBottom: 16,
    border: "1px solid #e4d8c7",
  },
  formBlock: {
    border: "1px solid #e4d8c7",
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    background: "#fffaf2",
  },
  questionEditRow: {
    display: "grid",
    gridTemplateColumns: "38px minmax(0, 1fr) 38px",
    gap: 10,
    alignItems: "stretch",
    marginBottom: 8,
  },
  questionDragHandle: {
    border: "1px solid #d6c7b4",
    borderRadius: 8,
    background: "#efe5d6",
    color: "#5f5448",
    cursor: "grab",
    fontWeight: 700,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    minHeight: 42,
  },
  iconButton: {
    border: "1px solid #fecaca",
    borderRadius: 8,
    background: "#fef2f2",
    color: "#b91c1c",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: 0,
  },
  questionDragHandleActive: {
    cursor: "grabbing",
    background: "#e7f0e5",
    borderColor: "#9ab39d",
    color: "#2f5b45",
  },
  questionTitle: {
    fontWeight: 600,
    fontSize: 15,
    marginBottom: 10,
    color: "#2f2a24",
  },
  answerRow: {
    display: "flex",
    gap: 8,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  photoCard: {
    border: "1px solid #e4d8c7",
    borderRadius: 10,
    padding: 10,
    background: "#fbf6ec",
  },
  photoPreview: {
    width: "100%",
    height: 110,
    objectFit: "cover",
    borderRadius: 8,
    display: "block",
  },
  bottomActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
    flexWrap: "wrap",
  },
};
