import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "Arial, sans-serif",
    background: "#f5f7fa",
    minHeight: "100vh",
    padding: "clamp(12px, 3vw, 24px)",
    boxSizing: "border-box",
  },
  card: {
    background: "#fff",
    borderRadius: 16,
    padding: "clamp(14px, 3vw, 20px)",
    boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
    maxWidth: 960,
    margin: "0 auto",
    width: "100%",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
  },
  input: {
    width: "100%",
    padding: 10,
    borderRadius: 10,
    border: "1px solid #d1d5db",
    fontSize: 16,
    boxSizing: "border-box",
    minWidth: 0,
  },
  button: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  secondaryButton: {
    background: "#e5e7eb",
    color: "#111827",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  title: {
    marginTop: 0,
    color: "#111827",
  },
  section: {
    border: "1px solid #e5e7eb",
    borderRadius: 14,
    padding: 14,
    marginTop: 14,
    background: "#fafafa",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  small: {
    color: "#6b7280",
    fontSize: 13,
  },
  error: {
    padding: 10,
    borderRadius: 10,
    background: "#fee2e2",
    color: "#991b1b",
    marginBottom: 12,
  },

  cardTitle: {
    marginTop: 0,
    marginBottom: 12,
    color: "#111827",
  },
  sectionTitle: {
    marginTop: 0,
    marginBottom: 10,
    color: "#111827",
  },
  field: {
    marginBottom: 14,
  },
  label: {
    display: "block",
    marginBottom: 6,
    fontWeight: 600,
    color: "#374151",
  },
  textarea: {
    width: "100%",
    minHeight: 90,
    padding: 10,
    borderRadius: 10,
    border: "1px solid #d1d5db",
    resize: "vertical",
    fontSize: 14,
    boxSizing: "border-box",
  },
  primaryButton: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
  },
  removeButton: {
    background: "#dc2626",
    color: "#fff",
    border: "none",
    padding: "6px 10px",
    borderRadius: 8,
    cursor: "pointer",
    marginTop: 8,
    fontSize: 12,
  },
  formInfo: {
    padding: 12,
    borderRadius: 12,
    background: "#f9fafb",
    marginBottom: 16,
    border: "1px solid #e5e7eb",
  },
  formBlock: {
    border: "1px solid #e5e7eb",
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    background: "#fff",
  },
  questionEditRow: {
    display: "grid",
    gridTemplateColumns: "38px minmax(0, 1fr) 38px",
    gap: 10,
    alignItems: "stretch",
    marginBottom: 8,
  },
  questionDragHandle: {
    border: "1px solid #d1d5db",
    borderRadius: 10,
    background: "#f3f4f6",
    color: "#4b5563",
    cursor: "grab",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    minHeight: 42,
  },
  iconButton: {
    border: "1px solid #fecaca",
    borderRadius: 10,
    background: "#fef2f2",
    color: "#b91c1c",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: 0,
  },
  questionDragHandleActive: {
    cursor: "grabbing",
    background: "#dbeafe",
    borderColor: "#93c5fd",
    color: "#1d4ed8",
  },
  questionTitle: {
    fontWeight: 700,
    fontSize: 16,
    marginBottom: 10,
    color: "#111827",
  },
  answerRow: {
    display: "flex",
    gap: 8,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  photoCard: {
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 10,
    background: "#fafafa",
  },
  photoPreview: {
    width: "100%",
    height: 110,
    objectFit: "cover",
    borderRadius: 10,
    display: "block",
  },
  bottomActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
    flexWrap: "wrap",
  },
};
