import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "Arial, sans-serif",
    background: "#f4efe5",
    minHeight: "100vh",
    padding: "clamp(12px, 3vw, 24px)",
    boxSizing: "border-box",
  },
  card: {
    background: "#fffaf0",
    borderRadius: 12,
    padding: "clamp(14px, 3vw, 20px)",
    boxShadow: "0 2px 12px rgba(62, 50, 35, 0.08)",
    maxWidth: 960,
    margin: "0 auto",
    width: "100%",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  row: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    minWidth: 0,
  },
  input: {
    width: "100%",
    padding: 10,
    borderRadius: 10,
    border: "1px solid #d7c7aa",
    fontSize: 16,
    boxSizing: "border-box",
    minWidth: 0,
  },
  button: {
    background: "#2f6f4e",
    color: "#fff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  secondaryButton: {
    background: "#e8deca",
    color: "#2f2a1f",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
    maxWidth: "100%",
    whiteSpace: "normal",
  },
  title: {
    marginTop: 0,
    color: "#243b2d",
  },
  section: {
    border: "1px solid #d8c7aa",
    borderRadius: 10,
    padding: 14,
    marginTop: 14,
    background: "#fbf6ea",
    overflow: "hidden",
    boxSizing: "border-box",
  },
  compactList: {
    display: "grid",
    gap: 8,
    marginTop: 12,
  },
  compactRow: {
    border: "1px solid #d8c7aa",
    borderRadius: 8,
    background: "#fffaf0",
    overflow: "hidden",
  },
  compactRowHeader: {
    width: "100%",
    border: "none",
    background: "transparent",
    padding: "10px 12px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 12,
    alignItems: "center",
    cursor: "pointer",
    textAlign: "left",
  },
  compactRowTitle: {
    display: "block",
    fontWeight: 700,
    color: "#243b2d",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  compactRowMeta: {
    display: "block",
    color: "#6f624e",
    fontSize: 13,
    marginTop: 2,
  },
  compactRowChevron: {
    color: "#2f6f4e",
    fontWeight: 800,
    fontSize: 18,
    lineHeight: 1,
  },
  compactRowBody: {
    borderTop: "1px solid #d8c7aa",
    padding: 12,
    background: "#f7eddc",
  },
  compactActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
  },
  small: {
    color: "#6f624e",
    fontSize: 13,
  },
  error: {
    padding: 10,
    borderRadius: 10,
    background: "#fee2e2",
    color: "#991b1b",
    marginBottom: 12,
  },

  cardTitle: {
    marginTop: 0,
    marginBottom: 12,
    color: "#243b2d",
  },
  sectionTitle: {
    marginTop: 0,
    marginBottom: 10,
    color: "#243b2d",
  },
  field: {
    marginBottom: 14,
  },
  label: {
    display: "block",
    marginBottom: 6,
    fontWeight: 600,
    color: "#4d4638",
  },
  textarea: {
    width: "100%",
    minHeight: 90,
    padding: 10,
    borderRadius: 10,
    border: "1px solid #d7c7aa",
    resize: "vertical",
    fontSize: 14,
    boxSizing: "border-box",
  },
  primaryButton: {
    background: "#2f6f4e",
    color: "#fff",
    border: "none",
    padding: "10px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontWeight: 700,
  },
  removeButton: {
    background: "#dc2626",
    color: "#fff",
    border: "none",
    padding: "6px 10px",
    borderRadius: 8,
    cursor: "pointer",
    marginTop: 8,
    fontSize: 12,
  },
  formInfo: {
    padding: 12,
    borderRadius: 12,
    background: "#f7eddc",
    marginBottom: 16,
    border: "1px solid #d8c7aa",
  },
  formBlock: {
    border: "1px solid #d8c7aa",
    borderRadius: 10,
    padding: 14,
    marginBottom: 16,
    background: "#fffaf0",
  },
  questionEditRow: {
    display: "grid",
    gridTemplateColumns: "38px minmax(0, 1fr) 38px",
    gap: 10,
    alignItems: "stretch",
    marginBottom: 8,
  },
  questionDragHandle: {
    border: "1px solid #d7c7aa",
    borderRadius: 10,
    background: "#e8deca",
    color: "#5b513f",
    cursor: "grab",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    userSelect: "none",
    minHeight: 42,
  },
  iconButton: {
    border: "1px solid #fecaca",
    borderRadius: 10,
    background: "#fef2f2",
    color: "#b91c1c",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 42,
    padding: 0,
  },
  questionDragHandleActive: {
    cursor: "grabbing",
    background: "#dbe9d2",
    borderColor: "#8fb87a",
    color: "#2f6f4e",
  },
  questionTitle: {
    fontWeight: 700,
    fontSize: 16,
    marginBottom: 10,
    color: "#243b2d",
  },
  answerRow: {
    display: "flex",
    gap: 8,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  photoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
    gap: 12,
    marginTop: 12,
  },
  photoCard: {
    border: "1px solid #d8c7aa",
    borderRadius: 10,
    padding: 10,
    background: "#fbf6ea",
  },
  photoPreview: {
    width: "100%",
    height: 110,
    objectFit: "cover",
    borderRadius: 10,
    display: "block",
  },
  bottomActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 20,
    flexWrap: "wrap",
  },
};
